name: CI/CD Pipeline – Horilla Demo (Django)

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/horilla_demo:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/horilla_demo:latest
          format: table
          exit-code: "0"   # change to "1" to fail on high/critical vulnerabilities
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/horilla_demo:latest
          
      - name: SonarQube Analysis 
        uses: sonarsource/sonarqube-scan-action@v2 
        with: 
          projectBaseDir: . 
          args: > 
            -Dsonar.projectKey=Horilla-Demo 
            -Dsonar.python.version=3.11 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 

